TRANSLATIONS = {
    "pt": {
        # Sidebar
        "my_tasks": " Minhas Tarefas",
        "blog": " Blog",
        "blog_notice": "⚠️ TOME NOTA",
        "blog_message": "Este programa foi desenvolvido por Julio Ormundo utilizando um modelo gerado por Inteligência Artificial. Ele é um protótipo educacional e pode conter limitações ou bugs. Use com cautela e mantenha backup dos seus dados.",
        "priority_low": "Baixa",
        "priority_medium": "Média",
        "priority_high": "Alta",
        "settings": " Configurações",
        "talk": " Fale Conosco",
        "logout": " Sair da Conta",

        # Dashboard
        "new_task": "+ Nova Tarefa",
        "search_placeholder": " Buscar por título ou descrição...",
        "stat_total": "Total",
        "stat_pending": "Pendentes",
        "stat_completed": "Concluídas",
        "stat_progress": "Progresso",

        # Configurações
        "theme_title": " Aparência e Tema",
        "lang_title": " Idioma / Language",
        "lang_desc": "Escolha o idioma da interface para o seu conforto.",
        "theme_desc": "Alterne entre tema escuro, claro ou seguir o sistema.",
        "export_title": " Backup e Exportação",
        "export_desc": "Exporte suas tarefas em JSON ou CSV para backup.",
        "export_json": "Exportar JSON",
        "export_csv": "Exportar CSV",
        "dark": "Escuro",
        "light": "Claro",
        "system": "Sistema",
        "export_success": "✓ Exportado com sucesso em: {path}",
        "export_error": "❌ Erro ao exportar: {error}",

        # Auth / Welcome
        "welcome_back_title": "👋 Olá, {username}!",
        "welcome_back_subtitle": "Bem-vindo de volta ao TaskFlow",
        "welcome_back_enter": "🚀 Entrar no TaskFlow",
        "welcome_back_switch": "Entrar com outra conta",
        "login_title": "TaskFlow",
        "login_subtitle": "Acesse ou crie sua conta para continuar",
        "login_mode_login": "Login",
        "login_mode_register": "Cadastrar",
        "login_username_placeholder": "Nome de usuário",
        "login_password_placeholder": "Senha",
        "login_submit_login": "Entrar",
        "login_submit_register": "Criar Conta",
        "auth_required_fields": "Preencha o nome de usuário e a senha.",
        "auth_username_min_length": "O nome de usuário deve ter pelo menos 3 caracteres.",
        "auth_password_min_length": "A senha deve ter pelo menos 4 caracteres.",
        "auth_username_taken": "Este nome de usuário já está em uso. Tente outro.",
        "auth_required_login": "Informe usuário e senha para entrar.",
        "auth_login_error": "Usuário ou senha incorretos.",

        # Dashboard labels
        "dashboard_title": "TaskFlow",
        "dashboard_subtitle": "Organize suas tarefas com prioridades e estatísticas dinâmicas",
        "dashboard_add_task": "+ Nova Tarefa",
        "dashboard_search_placeholder": "🔍 Buscar por título ou descrição...",
        "dashboard_filter_all": "Todas",
        "dashboard_filter_pending": "Pendentes",
        "dashboard_filter_completed": "Concluídas",
        "dashboard_filter_favorites": "Favoritas",
        "dashboard_empty": "Nenhuma tarefa encontrada.",
        "dashboard_empty_search": "Nenhum resultado para '{query}'.",
        "dashboard_created_at": "Criado em: {date}",
        "dashboard_complete": "Concluir",
        "dashboard_complete_alt": "Desfazer",
        "dashboard_edit": "✏️",
        "dashboard_delete": "🗑️",

        # Task dialog
        "task_dialog_title_new": "Nova Tarefa",
        "task_dialog_title_edit": "Editar Tarefa",
        "task_dialog_subtitle_new": "Adicionar Nova Tarefa",
        "task_dialog_subtitle_edit": "Editar Tarefa",
        "task_dialog_title_label": "Título:",
        "task_dialog_description_label": "Descrição:",
        "task_dialog_priority_label": "Prioridade:",
        "task_dialog_placeholder_title": "Ex: Estudar Python",
        "task_dialog_placeholder_description": "Detalhes da tarefa...",
        "task_dialog_save_new": "Adicionar Tarefa",
        "task_dialog_save_edit": "Salvar Alterações",
        "task_dialog_error_title": "O título é obrigatório.",
        "task_dialog_error_generic": "Não foi possível salvar a tarefa.",

        # Contact screen
        "contact_title": "Desenvolvido por Julio Ormundo",
        "contact_desc": "Tem dúvidas, encontrou um bug ou deseja dar um feedback sobre o TaskFlow? Entre em contato diretamente através de um dos canais abaixo:",
        "contact_email": "✉️ Enviar E-mail",
        "contact_github": "🐙 Ver GitHub",
        "contact_linkedin": "💼 LinkedIn",
    },
    "en": {
        # Sidebar
        "my_tasks": " My Tasks",
        "blog": " Blog",
        "blog_notice": "⚠️ TAKE NOTE",
        "blog_message": "This program was developed by Julio Ormundo using a model generated by Artificial Intelligence. It is an educational prototype and may contain limitations or bugs. Use it with caution and keep backups of your data.",
        "priority_low": "Low",
        "priority_medium": "Medium",
        "priority_high": "High",
        "settings": " Settings",
        "talk": " Contact Us",
        "logout": " Log Out",

        # Dashboard
        "new_task": "+ New Task",
        "search_placeholder": " Search by title or description...",
        "stat_total": "Total",
        "stat_pending": "Pending",
        "stat_completed": "Completed",
        "stat_progress": "Progress",

        # Configurações
        "theme_title": " Appearance & Theme",
        "lang_title": " Language / Idioma",
        "lang_desc": "Choose the interface language that suits you best.",
        "theme_desc": "Switch between dark, light, or system theme.",
        "export_title": " Backup & Export",
        "export_desc": "Export your tasks in JSON or CSV for backup.",
        "export_json": "Export JSON",
        "export_csv": "Export CSV",
        "dark": "Dark",
        "light": "Light",
        "system": "System",
        "export_success": "✓ Exported successfully to: {path}",
        "export_error": "❌ Export failed: {error}",

        # Auth / Welcome
        "welcome_back_title": "👋 Hello, {username}!",
        "welcome_back_subtitle": "Welcome back to TaskFlow",
        "welcome_back_enter": "🚀 Enter TaskFlow",
        "welcome_back_switch": "Sign in with another account",
        "login_title": "TaskFlow",
        "login_subtitle": "Sign in or create an account to continue",
        "login_mode_login": "Login",
        "login_mode_register": "Register",
        "login_username_placeholder": "Username",
        "login_password_placeholder": "Password",
        "login_submit_login": "Sign In",
        "login_submit_register": "Create Account",
        "auth_required_fields": "Please enter a username and password.",
        "auth_username_min_length": "The username must be at least 3 characters long.",
        "auth_password_min_length": "The password must be at least 4 characters long.",
        "auth_username_taken": "This username is already taken. Please try another one.",
        "auth_required_login": "Please enter your username and password to sign in.",
        "auth_login_error": "Incorrect username or password.",

        # Dashboard labels
        "dashboard_title": "TaskFlow",
        "dashboard_subtitle": "Organize your tasks with priorities and dynamic statistics",
        "dashboard_add_task": "+ New Task",
        "dashboard_search_placeholder": "🔍 Search by title or description...",
        "dashboard_filter_all": "All",
        "dashboard_filter_pending": "Pending",
        "dashboard_filter_completed": "Completed",
        "dashboard_filter_favorites": "Favorites",
        "dashboard_empty": "No tasks found.",
        "dashboard_empty_search": "No results for '{query}'.",
        "dashboard_created_at": "Created at: {date}",
        "dashboard_complete": "Complete",
        "dashboard_complete_alt": "Undo",
        "dashboard_edit": "✏️",
        "dashboard_delete": "🗑️",

        # Task dialog
        "task_dialog_title_new": "New Task",
        "task_dialog_title_edit": "Edit Task",
        "task_dialog_subtitle_new": "Add New Task",
        "task_dialog_subtitle_edit": "Edit Task",
        "task_dialog_title_label": "Title:",
        "task_dialog_description_label": "Description:",
        "task_dialog_priority_label": "Priority:",
        "task_dialog_placeholder_title": "e.g. Study Python",
        "task_dialog_placeholder_description": "Task details...",
        "task_dialog_save_new": "Add Task",
        "task_dialog_save_edit": "Save Changes",
        "task_dialog_error_title": "The title is required.",
        "task_dialog_error_generic": "Could not save the task.",

        # Contact screen
        "contact_title": "Developed by Julio Ormundo",
        "contact_desc": "Have questions, found a bug, or want to share feedback about TaskFlow? Reach out through one of the channels below:",
        "contact_email": "✉️ Send Email",
        "contact_github": "🐙 View GitHub",
        "contact_linkedin": "💼 LinkedIn",
    }
}

# Idioma padrão
CURRENT_LANG = "pt"


def set_language(lang_code: str):
    global CURRENT_LANG
    if lang_code in TRANSLATIONS:
        CURRENT_LANG = lang_code


def get_language_label(lang_code: str) -> str:
    return "English" if lang_code == "en" else "Português"


def t(key: str, **kwargs) -> str:
    """Retorna a tradução da chave no idioma atual."""
    value = TRANSLATIONS.get(CURRENT_LANG, {}).get(key, key)
    if kwargs:
        return value.format(**kwargs)
    return value